"""Add kampusJurusan

Revision ID: 450e00dee710
Revises: 4eaff61a47ae
Create Date: 2024-11-24 21:40:20.487934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '450e00dee710'
down_revision = '4eaff61a47ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_kampus_jurusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_kampus', sa.Integer(), nullable=False),
    sa.Column('id_jurusan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_jurusan'], ['tb_jurusan.id_jurusan'], ),
    sa.ForeignKeyConstraint(['id_kampus'], ['tb_mstkampus.id_kampus'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_jurusan', schema=None) as batch_op:
        batch_op.drop_constraint('tb_jurusan_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_kampus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_jurusan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_kampus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tb_jurusan_ibfk_1', 'tb_mstkampus', ['id_kampus'], ['id_kampus'])

    op.drop_table('tb_kampus_jurusan')
    # ### end Alembic commands ###
