"""Initial migration

Revision ID: d2828f2dbc13
Revises: 
Create Date: 2024-11-24 16:50:07.694376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2828f2dbc13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_provinsi',
    sa.Column('id_provinsi', sa.Integer(), nullable=False),
    sa.Column('nama_provinsi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_provinsi')
    )
    op.create_table('tb_santri',
    sa.Column('id_santri', sa.Integer(), nullable=False),
    sa.Column('nama_santri', sa.String(length=100), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=100), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=True),
    sa.Column('no_telp', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_santri')
    )
    op.create_table('tb_user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('tb_kampus',
    sa.Column('id_kampus', sa.Integer(), nullable=False),
    sa.Column('id_santri', sa.Integer(), nullable=False),
    sa.Column('nama_kampus', sa.String(length=100), nullable=True),
    sa.Column('jurusan', sa.String(length=100), nullable=True),
    sa.Column('program_studi', sa.String(length=100), nullable=True),
    sa.Column('organisasi_internal', sa.String(length=100), nullable=True),
    sa.Column('organisasi_eksternal', sa.String(length=100), nullable=True),
    sa.Column('nama_himpunan', sa.String(length=100), nullable=True),
    sa.Column('kota', sa.String(length=100), nullable=True),
    sa.Column('provinsi', sa.String(length=100), nullable=True),
    sa.Column('tahun_masuk', sa.Date(), nullable=False),
    sa.Column('perusahaan', sa.String(length=100), nullable=True),
    sa.Column('alamat_perusahaan', sa.String(length=100), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_santri'], ['tb_santri.id_santri'], ),
    sa.PrimaryKeyConstraint('id_kampus')
    )
    op.create_table('tb_kota',
    sa.Column('id_kota', sa.Integer(), nullable=False),
    sa.Column('nama_kota', sa.String(length=100), nullable=False),
    sa.Column('id_provinsi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_provinsi'], ['tb_provinsi.id_provinsi'], ),
    sa.PrimaryKeyConstraint('id_kota')
    )
    op.create_table('tb_lembaga',
    sa.Column('id_lembaga', sa.Integer(), nullable=False),
    sa.Column('id_santri', sa.Integer(), nullable=False),
    sa.Column('nama_lembaga', sa.String(length=100), nullable=True),
    sa.Column('jurusan', sa.String(length=100), nullable=True),
    sa.Column('tahun_masuk', sa.Date(), nullable=False),
    sa.Column('tahun_lulus', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_santri'], ['tb_santri.id_santri'], ),
    sa.PrimaryKeyConstraint('id_lembaga')
    )
    op.create_table('tb_mstkampus',
    sa.Column('id_kampus', sa.Integer(), nullable=False),
    sa.Column('nama_kampus', sa.String(length=100), nullable=False),
    sa.Column('alamat_kampus', sa.String(length=100), nullable=True),
    sa.Column('id_provinsi', sa.Integer(), nullable=False),
    sa.Column('id_kota', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kota'], ['tb_kota.id_kota'], ),
    sa.ForeignKeyConstraint(['id_provinsi'], ['tb_provinsi.id_provinsi'], ),
    sa.PrimaryKeyConstraint('id_kampus')
    )
    op.create_table('tb_jurusan',
    sa.Column('id_jurusan', sa.Integer(), nullable=False),
    sa.Column('nama_jurusan', sa.String(length=100), nullable=False),
    sa.Column('id_kampus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kampus'], ['tb_mstkampus.id_kampus'], ),
    sa.PrimaryKeyConstraint('id_jurusan')
    )
    op.create_table('tb_program_studi',
    sa.Column('id_program_studi', sa.Integer(), nullable=False),
    sa.Column('nama_program_studi', sa.String(length=100), nullable=False),
    sa.Column('id_jurusan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_jurusan'], ['tb_jurusan.id_jurusan'], ),
    sa.PrimaryKeyConstraint('id_program_studi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_program_studi')
    op.drop_table('tb_jurusan')
    op.drop_table('tb_mstkampus')
    op.drop_table('tb_lembaga')
    op.drop_table('tb_kota')
    op.drop_table('tb_kampus')
    op.drop_table('tb_user')
    op.drop_table('tb_santri')
    op.drop_table('tb_provinsi')
    # ### end Alembic commands ###
